import * as fs from 'fs';
import * as path from 'path';
import { fileExists, ensureDir } from '../utils/fileUtils';
import { logger } from '../utils/logger';

const HOOK_CONTENT = `#!/bin/sh
# agent-atlas pre-commit hook
# Auto-generated by agent-atlas. See https://github.com/sarfraznawaz2005/atlasai

npx agent-atlas update
git add .agent-atlas/
`;

const HOOK_MARKER = 'atlas-ai';

export function installGitHook(projectRoot: string): void {
  const gitDir = path.join(projectRoot, '.git');

  if (!fileExists(gitDir)) {
    logger.info('No .git directory found. Run `agent-atlas watch` to keep .agent-atlas/ up to date automatically.');
    return;
  }

  const hooksDir = path.join(gitDir, 'hooks');
  const hookPath = path.join(hooksDir, 'pre-commit');

  ensureDir(hooksDir);

  if (fileExists(hookPath)) {
    const existingContent = fs.readFileSync(hookPath, 'utf-8');
    if (existingContent.includes(HOOK_MARKER)) {
      logger.debug('Git pre-commit hook already contains atlas-ai update command. Skipping.');
      return;
    }

    // Append to existing hook
    const newContent = existingContent.trimEnd() + '\n\n' +
      `# agent-atlas update\nnpx agent-atlas update\ngit add .agent-atlas/\n`;
    fs.writeFileSync(hookPath, newContent, 'utf-8');
    makeExecutable(hookPath);
    logger.info('Appended atlas-ai update to existing pre-commit hook.');
    return;
  }

  // Create new hook
  fs.writeFileSync(hookPath, HOOK_CONTENT, 'utf-8');
  makeExecutable(hookPath);
  logger.info('Installed pre-commit git hook to auto-update .agent-atlas/ on commit.');
}

export function removeGitHook(projectRoot: string): void {
  const hookPath = path.join(projectRoot, '.git', 'hooks', 'pre-commit');

  if (!fileExists(hookPath)) return;

  const content = fs.readFileSync(hookPath, 'utf-8');
  if (!content.includes(HOOK_MARKER)) return;

  // If the entire file is just the atlas hook, remove it
  const withoutAtlas = content
    .replace(/\n\n# agent-atlas update\nnpx agent-atlas update\ngit add \.agent-atlas\/\n/g, '\n')
    .replace(HOOK_CONTENT, '');

  if (!withoutAtlas.trim() || withoutAtlas.trim() === '#!/bin/sh') {
    fs.unlinkSync(hookPath);
    logger.info('Removed atlas-ai pre-commit hook.');
  } else {
    fs.writeFileSync(hookPath, withoutAtlas, 'utf-8');
    makeExecutable(hookPath);
    logger.info('Removed atlas-ai update from pre-commit hook.');
  }
}

function makeExecutable(filePath: string): void {
  try {
    fs.chmodSync(filePath, '755');
  } catch {
    // On Windows, chmod may not be supported — that is okay
    logger.debug(`Could not chmod ${filePath} — this may be expected on Windows`);
  }
}
